apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: wonderland
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: wonderland
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: __ECR_REGISTRY__/wonderland-production-user-service:__IMAGE_TAG__
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4002
          envFrom:
            - configMapRef:
                name: wonderland-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wonderland-application
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
